### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by Mentors4EDU** [ethereumdegen/detroit-meta-web#1]
Probably a dumb question, but how do you run this locally?

**Comment by ethereumdegen** [comment]
Ha oh not at all.  So you just run .. yarn dev.    Yarn build will build the files (can host w vercel with one click) .  See package.json scripts

**Comment by ethereumdegen** [comment]
This is really just a standard react-vite-template

**Comment by Mentors4EDU** [comment]
Glad to know, I thought for some reason it was node.

**Comment by ethereumdegen** [comment]
Oh its node as well ! vite is a framework on top of node
